version: '3'

services:
# Setting up NodeJS application service using existing image of the app
  node-app:
    image: bradleywoods/node-app:v2
    container_name: node-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mongodb://mongo-database:27017/posts
    depends_on:
      - mongo-database

# Setting up Mongo database service using official Mongo 3.2 image
  mongo-database:
    image: mongo:3.2
    container_name: mongo-database
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongod.conf:/etc/mongod.conf

# Setting up Nginx reverse proxy service using official Nginx image
  nginx-reverse-proxy:
    image: nginx
    container_name: nginx-reverse-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
